# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-10.14'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- task: cake-build.cake.cake-build-task.Cake@0
  displayName: 'Build using Cake'
  inputs:
    verbosity: Normal